- name: hehehe APK
  run: ./gradlew assembleDebug --stacktrace

- name: Show outputs (debug)
  run: |
    echo "=== outputs tree ==="
    ls -la
    ls -la app || true
    ls -ლა app/build || true
    find . -maxdepth 6 -type d -name outputs -print
    echo "=== APK found ==="
    find . -type f -name "*.apk" -print

- name: Upload APK artifact
  uses: actions/upload-artifact@v4
  with:
    name: apk
    path: |
      **/*.apk
    if-no-files-found: error
